### ISSUE TITLE
Marshaling support?

### ISSUE THREAD

**Issue by forderud** [microsoft/xlang#136]
First, I have to say that I'm excited about this project and am hoping for this to mature into a cross-platform alternative to COM and WinRT.

One of the big strengths of COM is transparent support for out-of-process marshaling, provided that the interfaces are "automation" compatible. This have enabled my team to easily switch between in-process (for performance), and out-of-process deployment (for failure isolation) of the same SW with minimal SW changes.

Are there any similar plans for transparent out-of-process marshaling with "xlang"?

**Comment by devhawk** [comment]
Nothing more than early discussions yet. We have lots of other things to get to first. 

Personally, I'm of the opinion that APIs need to be designed correctly to work well in both in and out of process scenarios. This has been an issue in the past, however I think building good remotable APIs is easier today because of the broad availability of "await" style async processing in mainstream languages. I've even presented on this topic - Slides 20-27 of [Insert Funny Title ​About API Design Here](https://onedrive.live.com/view.aspx?resid=D9BC809858885A4!1241210&ithint=file%2cpptx&app=PowerPoint&authkey=!AOoertTJae03Ne8) from VSLive Redmond 2015 (sorry, no audio or video - just slides)

**Comment by forderud** [comment]
Please note that I'm not thinking about over-the-network remoting here. Just out-of-process communication on the same computer. With COM, it's possible to implement shared memory-based marshaling by implementing the [IMarshal](https://docs.microsoft.com/en-us/windows/desktop/api/objidl/nn-objidl-imarshal) interface. My experience is that this can eliminate copying overhead when exchanging large objects/buffers between processes, and reduce the marshaling overhead to basically a context switch.

I fully understand that this discussion might be a bit premature. Just wanted to flag that transparent marshaling is a valuable property that I would appreciate if could be part of the "xlang" roadmap.

**Comment by kennykerr** [comment]
Thanks for the feedback!

**Comment by forderud** [comment]
Related question: https://github.com/microsoft/xlang/issues/770
