### ISSUE TITLE
Eliminate code analysis warnings from project templates

### ISSUE THREAD

**Issue by Scottj1s** [Microsoft/xlang#208]
The VSIX project templates issue a number of CA warnings.  These should be suppressed or the code refactored so that newly created projects build and analyze warning free.

**Comment by sunnychatterjee** [comment]
Looking more into it, I see that the problem is the following task is not getting executed when you run code analysis on a C++/WinRT project:

1>Target "SetCABuildNativeEnvironmentVariables" in file "C:\Program Files (x86)\Microsoft Visual Studio\2019\Preview\MSBuild\Microsoft\VisualStudio\v16.0\CodeAnalysis\Microsoft.CodeAnalysis.targets":
1>  Task "SetEnv"
1>    Task Parameter:Value=C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VC\Tools\MSVC\14.16.27023\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um;
1>    Task Parameter:Name=CAExcludePath
1>    Task Parameter:Prefix=False
1>    CAExcludePath=C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VC\Tools\MSVC\14.16.27023\atlmfc\include;C:\Program Files (x86)\Microsoft Visual Studio\Preview\Enterprise\VC\Tools\MSVC\14.16.27023\include;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\ucrt;;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\um;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\shared;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\winrt;C:\Program Files (x86)\Windows Kits\10\Include\10.0.17763.0\cppwinrt;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um;C:\Program Files (x86)\Windows Kits\NETFXSDK\4.6.1\Include\um;
1>  Done executing task "SetEnv".
1>  Task "SetEnv"
1>    Task Parameter:Value=1
1>    Task Parameter:Name=CAEmitSarifLog
1>    Task Parameter:Prefix=False
1>    CAEmitSarifLog=1
1>  Done executing task "SetEnv".
1>Done building target "SetCABuildNativeEnvironmentVariables" in project "ConsoleApplication17.vcxproj".

The first environment variable 'CAExcludePath' makes sure warnings from %INCLUDE% headers don't get reported. The second environment variable 'CAEmitSarifLog' makes sure CA tools generate SARIF logs for populating the error list.

If we can get the task to execute, it would fix both the issues (the warnings won't be getting reported in the %INCLUDE% path and error list would get populated).

**Comment by sunnychatterjee** [comment]
I found the source of the bug. It's in Microsoft.Windows.CppWinRT.targets" (line 17 - line 19) where you are setting "PrepareForBuildDependsOn".

Current code looks like this:
        <PrepareForBuildDependsOn>
            CppWinRTVerifyKitVersion
        </PrepareForBuildDependsOn

Thus, the existing tasks get overridden with the WinRT task.

The fix is as follows:
        <PrepareForBuildDependsOn>
           $(PrepareForBuildDependsOn);
            CppWinRTVerifyKitVersion
        </PrepareForBuildDependsOn>

With this fix applied, I verified that we don't get any code analysis warning from WinRT project, since the system included headers get excluded from analysis.
