### ISSUE TITLE
[Question] xLang vs .NET

### ISSUE THREAD

**Issue by stevenbrix** [Microsoft/xlang#220]
xLang seems super awesome, and I'm curious how it is conceptually different than .NET and the CLR. Are they two different solutions to the same problem? I'm thinking at a very high level here, and not entirely concerned with what is/isn't supported, mostly just interested in what problem's they are solving

**Comment by devhawk** [comment]
xlang isn't an execution environment like .NET. xlang defines an OO type system that can be mapped to a variety of OO languages (I often refer to it as a "primoridal" type system). xlang also specifies the stable binary interface to enable interop across binary boundaries. Finally, xlang specifies a metadata representation of the types in a given binary so that language specific mappings (called "projections") can be generated by tools. 

Further details are availavble in [XDN01 - A Strategy for Language Interoperability](https://github.com/Microsoft/xlang/blob/master/design_notes/XDN01%20-%20A%20Strategy%20for%20Language%20Interoperability.md)

**Comment by devhawk** [comment]
FYI, I'm closing this issue. @stevenbrix please feel free to ping me to reopen it if I haven't addressed your questions
