### ISSUE TITLE
cppwinrt.exe -in option has file name case dependent behavior, add option to opt out

### ISSUE THREAD

**Issue by ChrisGuzak** [microsoft/xlang#309]
These two commands result different output.
cppwinrt.exe -component d:\temp\good\component -in windowsudk.winmd -out d:\temp\good
cppwinrt.exe -component d:\temp\bad\component -in WindowsUdk.winmd -out d:\temp\bad
 
By changing the filename case, generated stub file structure is different.

Kenny says this is by design and can't be changed. but I recommend adding a -no-winmd-namespace-mapping option that is an opportunity to identify this behavior and allow clients to opt out of it.

**Comment by kennykerr** [comment]
Well I said this was by design and couldn't immediately be changed (when bringing up 2.0) but my goal is to simplify the command line parsing and actually remove this quirk now that the `-name` option is available to deal with this properly. In fact, the `-name` option has been available for a long time. I may simply remove this subtle behavior and add a warning to help diagnose any build breaks.

**Comment by ChrisGuzak** [comment]
sounds good to me.
