### ISSUE TITLE
Is compatibility with the Windows Runtime a goal of the project?

### ISSUE THREAD

**Issue by ArmsOfSorrow** [Microsoft/xlang#31]
I'm mostly asking about the way language projections work. For example if I write a tool that generates Rust code akin to the C++/Python ones, will it work with today's Windows Runtime APIs?

**Comment by BenJKuhn** [comment]
Compatibility was something that we orginally hoped to preserve. We eventually dropped it and chose to diverge so that we could make a few key breaking changes that should make the system more usable from a larger set of languages and platforms. One of the key motivators was supporting UTF-8 strings across the ABI, though there are a few other differences as well.

Having said that, we are staying closely aligned in ways that will help both component authors and consumers.

You should find it easy to adapt libraries and projection tools from one to the other. Most concepts will map 1:1. In theory, we also expect it to be possible to surface both sets of interfaces from a single object. However, the type systems are separate, type lookup will work differently, and the base C APIs used support projections are separate.

From the perspective of someone consuming the two systems, projections for winrt and xlang will mostly hide the differences. E.g. C++ /WinRT and C++ xlang types will both be created using C++ new and methods will be called through a dot '.' operator.

Ben
