### ISSUE TITLE
 <CppWinRTUsePrefixes>false</CppWinRTUsePrefixes> does'nt work for module.g.cpp includes

### ISSUE THREAD

**Issue by mediabuff** [microsoft/xlang#315]
-prefix             Use dotted namespace convention for component files (defaults to folders)

Please see blew "Core.BitmapDrawer.h", it should be "Core/BitmapDrawer.h

// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.190408.1

#include "pch.h"
#include "winrt/base.h"
#include "Core.BitmapDrawer.h"

**Comment by kennykerr** [comment]
This is by design. The -prefix option only affects the generated headers, not your own. It is a quirk of the command line that we support for compatibility with some older projects. Ideally you should use -prefix (leave it on) and ignore the other confusing behavior. I hope to remove it in a future update.

**Comment by mediabuff** [comment]
Kenny, thanks for the quick reply. I would like to keep my source files organized under a directory hierarchy that mimics the namespace. Having the hard time cppwinrt support this org structure of source files.

**Comment by kennykerr** [comment]
Sure thing. I'm working on improving the overall project/layout support. I'll keep this in mind. I know some teams do prefer this.

**Comment by mediabuff** [comment]
thank you. Some thing like this

namespace core::BitmapDrawer

#include "Core/BitmapDrawer.h"
