### ISSUE TITLE
UNIX line endings (`CR`) in generated source files from IDL

### ISSUE THREAD

**Issue by tim-weis** [Microsoft/xlang#355]
Using the VSIX (2.0.190417.3) to generate stub implementations from an IDL produces source and header files with UNIX (`CR`) line endings. Those stubs are meant to be copied, introducing the need to clean up the inconsistent line endings (Visual Studio uses `CR LF` by default) at some point. 

Can we get the VSIX to generate Windows line endings (`CR LF`) by default?

**Comment by kennykerr** [comment]
Thanks Tim, the real problem is that the Visual Studio editor should maintain the original file's line ending when mismatched line ending text is pasted into it. VS Code handles this automatically and seamlessly (as does every other editor I use). This has been reported to the Visual Studio team in various forums but they would like to see more customer demand before fixing this. The best way to get their attention is to report the problem here:

[developercommunity.visualstudio.com](https://developercommunity.visualstudio.com/spaces/8/index.html)

Feel free to provide a link to your bug report here and hopefully enough people (like me) will upvote the issue and they will get this fixed. For reference, the internal DevDiv bug number for this issue is 474058.

**Comment by kennykerr** [comment]
Update: I spoke to the Visual Studio team about this and they have commited to fixing this problem very soon.

**Comment by tim-weis** [comment]
I'd had to let this settle for a bit in the hopes of finding the right words, but all I came up with is this: 

**Thank you!**

Not just for setting me straight on what my *real* issue was, but even more so for going the extra mile by initiating (or at least giving feedback on) a solution. That is much appreciated.
