### ISSUE TITLE
Roadmap for Xlang project?

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/xlang#368]
I have been following the Xlang project since it was published. I believe you're doing a great job! This is a very much needed project in my opinion.

Do you have any high-level roadmap? I understand that so far your focus had been to release C++/WinRT 2.0, I guess, to support some product teams inside Microsoft itself.

Do you have any estimation on when and how you will be releasing Xlang bits for other platforms? I'm particularly interested in older Windows versions (7+) and Unix platforms.

By “high-level” plan I mean something like “beta until the end of this year” or “currently we plan to release it by the time of .NET Core 3.0/4.0/X.Y GA”. “We'll talk more about it at Build in a week” also works :)

**Comment by BenJKuhn** [comment]
As you've probably seen, this is an ambitious project, and there are multiple efforts happening on different fronts. We do have specific aspects that we're trying to bring up sooner rather than later, often in support of partners that aren't publicly announcing their work. If you're looking for an answer of when "xlang 1.0" is going to be declared, I can't give you a date, but it's going to be a while. If there are specific pieces that you'd like to see come together in support of something that you're working on, please feel free to reach out to me privately by email at benkuhn at Microsoft.

I can give a bit more of a high-level overview of what's happening at the moment. The longer roadmap is changing based on customer asks & needs so I don't want to project too far out.

There are two main workstreams within the project, xlang and winrt. Keep in mind that our team also supports other aspects of the Windows developer experience, so progress will sometimes slow as other things demand our time.

**For WinRT**
Harry (devhawk) has been primarily focusing on getting Python out the door. Most things are working well and we've published a preview version, but there's still work to do to support XAML types and implementing types.

Kenny & Scott are continuing to drive improvements to the C++ WinRT experience.

Scott has started prototyping a Java developer experience for WinRT.

Tomas Morris (not a member of my team) has started writing a typescript tool for winrt. While we welcome his contribution, we have no control over his time or schedule.

**For xlang**
The biggest challenge is the type system. While we're borrowing heavily from WinRT, there's a lot that we've learned about how it works in practice, and we're making sure that xlang doesn't inherit some of the more challenging limitations. We're developing this through the design note process [here](https://github.com/Microsoft/xlang/blob/master/design_notes/XDN00%20-%20Design%20Note%20Process.md) and moving at a thoughtful pace. Harry (devhawk) is driving, and might be able to publish at least a partial road-map of topics that we're going to tackle in the near future. We have enough in place that we've been able to start laying code down though.

We're currently building for Ubuntu and Windows using clang & VC respectively to keep ourselves honest about writing portable code. I suspect our current xlang infrastructure would run down to Windows 7 but we don't have automation in place to validate that yet.

Ryan has been working on establishing the platform abstraction layer & port of Cpp WinRT to cppxlang

Will is working on a type definition tool similar to midlrt that will support xlang metadata without all the classic IDL & COM baggage.

Most other language projections that we're building leverage C++ /WinRT or C++ /xlang as a part of the tooling. Once we have C++ xlang running against a portable PAL, we intend introducing more languages in the xlang family by porting the WinRT versions.

C# support is pretty high on the wish list, though I can't commit to a timeline yet. ;)

We welcome community contributions on any and all aspects of the project. If you'd like to coordinate a bit before submitting a pull request, drop me an email.

I hope that gives a bit better picture.

Thanks,

Ben

**Comment by raffaeler** [comment]
@BenJKuhn Thanks for the overview.
I already talked in person with Kenny and Harry about the possible steps to bridge nodejs where I have a personal experience for a similar project I created.

But can you share some technical roadmap behind .NET support? In other words, what are the steps desired/needed to go there?
It would be extremely useful for an open source project to split those steps so that any contribution can go in the same direction.

**Comment by BenJKuhn** [comment]
Our current thinking is to follow the same basic roadmap that Harry used for building the python support. It'll be a generated adapter assembly instead of the built-in support that WinRT has in the CLR. 

Having the WinRT support integrated in the CLR up to this point has had mixed results. It makes the developer experience a bit easier, but at the cost of being more challenging to add features. We think that the library approach will be more flexible and allow better reach, so we're leaning towards that approach.

I'll poll the team and see if there are more details that I can share about their thinking for how to tackle this. I know there have been some water cooler discussions, but nothing formal or written down yet.

Ben

**Comment by raffaeler** [comment]
Thanks Ben, I am a strong believer in interoperability, thus my intrerest in this great project.
Now that .NET introduced powerful mechanism to use native memory as it was managed (read Span<T>, Memory<T> and C# 7.x ref structs), there is a great opportunity to make the interop with C# more performant. I hope xlang will go in this direction.

**Comment by Alovchin91** [comment]
@BenJKuhn Thank you for an amazing overview!

It would be extremely cool if we could have say monthly overview updates similar to this one regarding direction, roadmap and progress of the project! ;)

The most important thing about xlang for me is the ability to replace C++/CLI and code generation tools with a thin layer of glue that will allow a seamless interop between .NET (C#) code and native libraries that will work cross-platform on different flavors of .NET. I believe xlang would be the best-ever tool to accomplish this task. It is perfectly fine with me that it would require a bit of C++ code, so even a Rust projection is not that necessary ;)

In this regard, I like the approach you are talking about of making xlang a separate adapter for C# rather than a CLR feature, because I hope it to run on .NET Framework (on Windows 7) and Mono (Unix) in addition to .NET Core, and that I won't have to move to an unreleased version of .NET Core to actually use it.

My biggest concert about xlang is actually a commitment, because, well, nowadays Microsoft is well-known to drop ambitious long-running projects that don't seem to have immediate value. I hope that the fact that your partner are actually working with you on xlang makes it more future-proof and it'll eventually see the light of day :)

I would definitely like to reach out to you by email to talk a bit about challenges I face and how I see xlang helping me to solve them. I'll drop you an email when I'm ready to talk about it in more detail :)

I hope this feedback would give you an impression of what I personally am waiting for. But first things first - as I said, please consider some monthly (or quarterly) roadmap/project overview updates in this tremendously useful form that we see here 👍

**Comment by BrentRe** [comment]
@raffaeler The approach we want to use for C# interop requires C# 8.0 but has the advantages that it doesn't require any new support from the CLR, so our interop code can run on all versions of .NET Desktop, .NET Core and Mono. Here's a proposed example (all xlang function names likely to change):

~~~C#
    public sealed class MyComponent
    {
        private void* _ptr;
 
        public MyComponent()
        {
            _ptr = Xlang.CreateObject(“MyNamespace.MyComponent”);
        }
 
        ~MyComponent() => Dispose();
 
        void Dispose() => Xlang.ReleaseObject(ref _ptr);
 
        // This is using C# 8 calli intrinsic https://github.com/dotnet/csharplang/blob/master/proposals/intrinsics.md .
        // Note that this feature works on existing VMs.
        // It is possible to achieve the same effect using earlier C# versions as well, but it is more cumbersome.
        [CallIndirect(default(CallingConvention))]
        private extern static int _MyMethod(void* thisPtr, int argument, void* pfn);
 
        public void MyMethod(int argument)
        {
            // MyMethod is placed in 3rd vtable slot according to Langworthy ABI rules
            Xlang.CheckResult(_MyMethod(_ptr, argument, *(*(void***)_ptr + 2));
        }
    }

**Comment by raffaeler** [comment]
@BrentRe looks great! We are living in exciting times.
I am already working with C#8 and previous goodies that make interop much faster than in the past.

I am definitely eager to play with the first previews asap. Any idea on when will you/the team start to work on it (without any committment of course)?

**Comment by kennykerr** [comment]
Scott has started working on C# support, but it is not as yet a committed project.
