### ISSUE TITLE
C++/WinRT defined enum operators is defined in global namespace so ADL isn't applied

### ISSUE THREAD

**Issue by mithrandir** [microsoft/xlang#417]
C++/WinRT defines enum operators in global namespace, in base.h. The problem is it doesn't work well if other code is relying on ADL for operator lookup, e.g, WIL. We may mitigate from the client code, but if C++/WinRT can define the enum operators per namespace, then we can relying on ADL so it should be more flexible

**Comment by kennykerr** [comment]
Since C++/WinRT generates enums in numerous namespaces (and generates many individual enum classes) it would result in substantially more code gen to generate operators per namespace and type. Since it is trivial to support C++/WinRT enums from WIL, it makes more sense for the WIL macros to be updated to accommodate C++/WinRT. 

https://github.com/microsoft/wil/issues/45

**Comment by dunhor** [comment]
This breaks more scenarios that just WIL

**Comment by kennykerr** [comment]
@dunhor I've only ever heard of this affecting WIL. I'm back in the office - let's chat.

**Comment by kennykerr** [comment]
Duncan provided a repro offline where this affects other scenarios than just WIL so I will go ahead and update C++/WinRT to be less clever and just emit the operators for all flag enums directly.
