### ISSUE TITLE
Synchronization primitives are undocumented

### ISSUE THREAD

**Issue by arkrumbe** [microsoft/xlang#476]
Types like `slim_mutex` and other synchronization primitives like the ones used [here](https://msdn.microsoft.com/en-us/magazine/mt846728.aspx) are undocumented in MSDN or this repo. I'd very much like to use these types myself, but have no means for understanding the API.

**Comment by kennykerr** [comment]
The `winrt::slim_xxx` types are just low-level wrappers around the Windows synchronization primitives. You're generally better off using the standard thread support library:

https://en.cppreference.com/w/cpp/thread

**Comment by arkrumbe** [comment]
Sure, but for internal users in MS (read: me) and to the same extent, developers using C++/WinRT, I wouldn't mind an RAII wrapper around one of those low-level primitives. In any event, using them in a blog post and expecting users to guess the semantics doesn't feel right to me. Can we move behind an internal namespace or document them for use?

**Comment by kennykerr** [comment]
The plan is to deprecate and remove them eventually, as the standard library alternatives are drop-in replacements (which also means you can figure out how to use them by looking at the documentation on cppreference). They exist today because of some performance issues with the standard library alternatives that will hopefully be resolved at some point.
