### ISSUE TITLE
C++/Winrt app incompatible with current Win 10 1803 build 17134

### ISSUE THREAD

**Issue by jevansAN** [microsoft/xlang#511]
My app runs fine on the development platform if I set the target to 17763 and the minimum to 17134. And the app certifies fine for the store. But the app downloaded to a Win Home version 1803 build 17134 crashes at launch. I think I have located the problem by setting the target to 17134: this produces a build error: 
"Unresolved external symbol _WINRT_CoincrementMTAUsage@4" at the first line of the first .obj in the program.
I can't tell if this is something related to C++/winrt specifically or winrt in general - but it certainly is a dealbreaker for my app, all build on the same Solution. Is there any fix available or on the horizon? I am building with VS 16.1.6 and C++/winrt version 2.0.190620.2.

**Comment by kennykerr** [comment]
It's unlikely that `CoIncrementMTAUsage` is causing your app to crash. The linker issue is that the `windowsapp.lib` that shipped with older SDKs didn't include an entry for `CoIncrementMTAUsage`. That was first added to `windowsapp.lib` in version 17763 of the SDK. It's likely that you're just calling some API that is not available on 17134. I suggest you debug the app on the target OS version to find out which API call is failing. If you're just testing locally you can link with `onecore.lib` instead of `windowsapp.lib` as the former should have an entry for `CoIncrementMTAUsage` going back to 17134.

**Comment by jevansAN** [comment]
Thanks - I had assumed that VS would complain if I called an API not available in the minimum OS version (never have quite understood the difference between Minimum OS and Target OS anyway). But  if the cause is my calling a future API I'm curious how this crash can occur before even leaving the splash screen. But I'll need to find out how to link with onecore.lib.

**Comment by jevansAN** [comment]
If it will help the readership: after a lot of searching I think the trouble was my use of the IsOpen() method of MenuFlyout, which I see was introduced in 17763. I had thought that VS would flag me if I used an API not available in the OS build set as the "minimum" for the app. Apparently not!
