### ISSUE TITLE
Revisit string encoding decision

### ISSUE THREAD

**Issue by devhawk** [microsoft/xlang#53]
WinRT uses UTF-16 encoded strings. Since xlang is not attempting to be binary compatible with WinRT, we can revisit this decision. In particular, we can consider several options

1. sticking with UTF16 encoded strings
2. changing to UTF8 encoded strings
3. Update string type + ABI to support UTF8 and UTF16 with conversion between the encodings

**Comment by phoyd** [comment]
UTF-16 always feeled to me like kind of legacy encoding, an echo from the time before Unicode, when UCS-2 was used for multilingual text and then upgraded to UTF-16 to support the full code point range, while breaking as little client code as possible. It doesn't make anything easier, because it is still not a fixed width encoding and I haven't seen much of it outside of the Windows-APIs. Most of Unix/Internet development has settled with UTF-8 and forcing UTF-16 to them will raise eyebrows.

**Comment by devhawk** [comment]
Looks like JNI supports both 8 and 16 bit strings. [NewString](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#wp4925) constructs a jstring from an array of 16-bit jchars while [NewStringUTF](https://docs.oracle.com/javase/7/docs/technotes/guides/jni/spec/functions.html#wp17220) constructs a jstring from an array of 8-bit chars.

**Comment by kennykerr** [comment]
The question is what encoding does it use internally to ensure good performance (and avoid copies).

**Comment by DHowett-MSFT** [comment]
JNI uses "Modified UTF-8", which is unfortunately just far enough away from UTF-8 as to be an annoyance.

**Comment by zooba** [comment]
Internally, CPython uses adaptive allocation so that it does "direct" encoding in code units with no surrogates or multi-element characters. But other implementations just use UTF-8 and are fine.

Part of the problem with both UTF-8 and UTF-16 is that malloc() and (Unicode-aware) strlen() do not use the same values, and the semantics of how they fail to give the same result are different between contexts (in Python, you'll get a reallocation/copy into a larger unit size, while in Windows it will pretend that surrogate pairs are independent characters unless you happen to get unlucky and hit something that properly validates the string).

So the simplest option to me seems to be choosing one representation for the ABI and let projections handle this as efficiently as they can, since they are in the best place to do this (for example, keeping the original around for round-tripping, lazily generating the language-specific representation, etc.).

I'd recommend UTF-8 (which didn't exist at the time Windows NT went with 16-bit Unicode that was later renamed UCS-2 and UTF-16).

**Comment by Elronnd** [comment]
IMO the only thing that makes sense is going utf8-only.  A given language can handle re-encoding if it wants.

**Comment by raffaeler** [comment]
.NET currently uses UTF-16 but it is a long time there are discussions. It would be definitely possible to even change it to UTF-8 as the internal format has never been exposed. The other option would be to introduce a new string primitive (which is available on GitHub as experimental).
My preference goes to UTF-8 only, with primitives to convert to other encodings.

I am wondering what Windows will ever want to do, now that most of the integrations happen on UTF8

**Comment by BenJKuhn** [comment]
The "type" of the string in xlang is an opaque handle in part so that we can change the underlying storage type if it makes sense at some point. As you can see form this [file](https://github.com/Microsoft/xlang/blob/master/src/platform/string_abi.cpp), we actually support operation on both UTF-8 and UTF-16 with conversion support. How the runtime stores that data now or in the future can be based on actual usage patterns, configurable, dynamic, adaptive, etc. and can change. By using a handle for interchange rather than raw data, we preserve the full range of possibilities even as we do something simple (picking a winner) for our initial bring-up of the project.

A survey of different languages and runtimes will show a healthy mix of UTF-8 and UTF-16, with a smattering of unhealthy crazy things in the mix as well. Any solution that picks a single winner is going to make some set of scenarios unnecessarily penalized. We've picked a "winner" for now as we work through basic bring up, but I know there's room for improvement here using a more dynamic approach. If anyone wants to jump in and add more PAL support for managing the underlying string storage in a configurable or dynamic way, take a run at it. I'd love to see what you come up with.

Ben
