### ISSUE TITLE
[Suggestion] Default unsealed runtimeclasses

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/xlang#64]
Since this project is not aiming to preserve binary compatibility with Windows Runtime and port Windows APIs, I would like to suggest making all the runtimeclasses unsealed by default.

This makes sence since there are no more Windows.* base classes that are required for WinRT unsealed classes, and this also aligns Xlang runtimeclasses with all the other languages.

This would require some changes to MIDL 3.0 — first of all, introduction of `sealed` keyword, but I believe it’s a must to get rid of this artificial limitation.

**Comment by Alovchin91** [comment]
@kennykerr That’s fair enough point, though still not clear what are the runtime costs, especially since they are used constantly in UWP XAML UI. Maybe that could become something like a poll? Or you are aiming to not to change MIDL specification? Thanks!

**Comment by kennykerr** [comment]
We're doing a lot of work to reduce those costs for xlang but they are still real - I have a TODO to describe that and publish that information here in the repo when I get a chance. Briefly, it stems from how the WinRT/xlang ABI is constructed, rather than IDL. IDL is just the current way to define metadata textually such that a binary metadata representation (ECMA-335) can be produced, commonly known as a winmd file. This binary format is the canonical way of describing the type system. WinRT and xlang then has a set of rules that transform that into a COM-based ABI.

**Comment by devhawk** [comment]
@Alovchin91 assuming xlang will supports type hierarchies, do you feel it's important that xlang types are unsealed *by default*? As @kennykerr said, there is additional cost for supporting type hierarchies, so I'd rather see them sealed by default, while giving the developer the choice to opt-in to inheritance support. Perhaps we could introduce an unsealed attribute in MIDL? It's the inverse of how ECMA 335 based metadata is encoded, but I think it would be a good approach for xlang.

**Comment by Alovchin91** [comment]
@devhawk The `unsealed` keyword is already present in MIDL 3.0, so it's already perfectly possible to create an unsealed class. I just thought that for the sake of conformance with all the other languages it would be better to have `runtimeclass`es unsealed by default, meaning without a keyword.

This problem could be solved by having a template with `sealed` keywords already present and something like "best practices" document. Your point is also quite understandable though, so I won't argue on this. It might be worth introducing something non-conformant in this case.
