### ISSUE TITLE
[Suggestion] Introduce Int8 MIDL type

### ISSUE THREAD

**Issue by Alovchin91** [microsoft/xlang#65]
Since this project is not aiming to preserve binary compatibility with Windows Runtime, I would like to suggest introducing signed 8-byte `Int8` primitive type into Xlang type system.

Current MIDL 3.0 doesn’t support Int8 type, and only has unsigned 8-bit integer type. But introducing the signed one would make a lot of sence if you expect to support UTF-8 strings in Xlang ABI.

This would require changes to MIDL 3.0 definition language of course.

**Comment by kennykerr** [comment]
A signed 8-bit integer was not considered useful by the original WinRT architects. We may revisit that since the underlying ECMA-335 spec certainly supports it. Thanks for the suggestion!

**Comment by Alovchin91** [comment]
@BrentRe Basically I currently use them to return strings (`sbyte*` arrays) allocated in a specific memory pool (not with .NET Marshal) back to the C# caller. They are easily converted to managed strings using just a String constructor.

That might not be a viable case for Xlang, but I think other users could also give some insights into how they could use them.

**Comment by fdwr** [comment]
The lack of actual signed 8-bit quantities in WinRT was annoying for implementing WinML tensors of that data type (see the INT8 data here for the ONNX Machine Learning format, https://github.com/onnx/onnx/blob/master/onnx/onnx.proto). Tensors are multidimensional arrays of data types, and we shouldn't need to reinterpret_cast int8_t to an array of unsigned char (which semantically doesn't really make sense) when it should be possible to just pass the array_view<int8_t> directly to WinRT API's. The data type is actually used, as quantized tensors greatly reduce multimegabyte model files. I wouldn't want to see XLang have the same limitation, especially given it's intended to have even broader interop.

>UTF-8 encodes all 1,112,064 valid code points in Unicode
Yeah, I see no use for signed bytes as code points and would discourage that (Unicode should always be unsigned), but I see other numeric processing uses outside machine learning too (e.g. signed 8-bit types used in older audio formats, like 8-bit PCM and telephony from ITU-T Recommendation G.711).

They are a basic data type in:
- Python numpy int8 - https://docs.scipy.org/doc/numpy/user/basics.types.html
- C++ int8_t - https://en.cppreference.com/w/cpp/types/integer
- Java byte (though arguably awful that Java made 'byte' signed by default, rather than a distinct sbyte type).
- C# sbyte - https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/sbyte

**Comment by BrentRe** [comment]
Given this data, I'm inclined to support Int8 in the xlang type system. Thanks.

We'll need to figure out the xlang <--> Windows Runtime interop story for types using Int8 but we should be able to do something reasonable.
