### ISSUE TITLE
Make it easy register WinRT event handlers using a WNDPROC

### ISSUE THREAD

**Issue by jeffstall** [microsoft/xlang#673]
Traditional Win32 UI code uses a WNDPROC to receive events. This defines important things, including:
1. Priority levels that are integrated with the UI stack.
2. Avoids ambiguity about receiving events on the MTA or using COM marshaling complexities to the STA.
3. Very lightweight compared with WinRT event delegates, and allows a single WNDPROC instance to service multiple events.

Normal usage:

- Raw function pointer with context
- Pointer-to-member for static function
- Pointer-to-member for C++ instance member
- Callback weak interface (avoid cycles references)
- Lambda are very new and not yet typical for Win32 UI C++ apps. This is more common for .NET WinForms and WPF, which has used delegates from the beginning.

**Comment by FrancisHogle** [comment]
Please note that we need to accommodate multiple actual signatures including:
- WNDPROC
- DLGPROC
- TIMERPROC
- ...

**Comment by jonwis** [comment]
It might help frame what you want by providing some samples.  What about:

```c++
auto catalog = winrt::PackageCatalog::OpenForCurrentUser();
g_catalogcookie = catalog.PackageInstalling(HwndEvent(g_mainWindow, WM_USER_PACKAGE_INSTALLING));
```

And later:

```c++
switch (msg) {
case WM_USER_PACKAGE_INSTALLING:
{
    auto payload = HwndEventArgs<PackageCatalog::PackageInstalling>(lParam);
    auto catalog = payload.Sender();
    auto args = payload.EventArgs();
    if (args.IsComplete() && InterestingPackage(args.Package())) {
       SetForegroundWindow(g_mainWindow);
    }
    break;
}
}
```

**Comment by ChrisGuzak** [comment]
this seems worse than providing a strongly typed delegate. what is the point?

**Comment by jonwis** [comment]
@ChrisGuzak - I'm proposing that strongly-typed delegate, `HwndEvent`, whose job is to handle the incoming `Invoke` from the APC thread on which the package installation event was delivered, then reflect it over to the `WndProc` for `g_mainWindow`.

In my mind, the `Invoke` implementation called by `CPackageCatalog` needs to "make it right" ... so that `Invoke` packs up the parameters and sends a `WM_WHATEVER`.

So the `HwndEvent` or `FuncCallEvent` types _enable_ strong typing without requiring developers split their logic into "the part that handles the WinRT event" and "the part on the wndproc that reacts" and "the part that bridges between the two."
