### ISSUE TITLE
WinRT structs need standard capabilities

### ISSUE THREAD

**Issue by jeffstall** [microsoft/xlang#674]
WinRT structs are pretty anemic. Out-of-band finally allows adding new fields, which makes structs much better for lightweight objects like various EventArgs. To make this possible, we need more than only field access, such as enable instance / static members for properties, methods, and events.

**Comment by Jaiganeshkumaran** [comment]
WinRT structs are just defined, they are not implemented by any component.

**Comment by Jaiganeshkumaran** [comment]
The built-in XAML struct types such as Color and Thickness have additional static methods when accessed through C# because the language projection adds those methods. Maybe there could be an attribute that makes static methods/properties/events on a helper class available from the struct type since struct types can't have an implementation.
