### ISSUE TITLE
_winrt.init_apartment() RuntimeError: Cannot change thread mode after it is set.

### ISSUE THREAD

**Issue by pbvinoth** [microsoft/xlang#690]
Hi All,

We are trying to invoke winrt apis using remote rpyc calls in remote machine. When we tried to inistialize the
objects we faced error 
Error added: <Error: _get_exception_class.<locals>.Derived: Cannot change thread mode after it is set.
RuntimeError: Cannot change thread mode after it is set.

        remote_wf = self._dev.rpyc.modules.winrt
        slash.logger.info("winrt init done")
        u = remote_wf.Uri("https://github.com/")
        u2 = u.combine_uri("Microsoft/xlang/tree/master/src/tool/python")
        print(str(u2))

and observed the following error in call stack
========= Remote Traceback (1) =========
Traceback (most recent call last):
  File "C:\Users\itl\pytm_win\pytm_win\lib\site-packages\rpyc\core\protocol.py", line 323, in _dispatch_request
    res = self._HANDLERS[handler](self, *args)
  File "C:\Users\itl\pytm_win\pytm_win\lib\site-packages\rpyc\core\protocol.py", line 585, in _handle_call
    return obj(*args, **dict(kwargs))
  File "C:\Users\itl\pytm_win\pytm_win\lib\site-packages\rpyc\core\service.py", line 160, in getmodule
    return __import__(name, None, None, "*")
  File "C:\Users\itl\pytm_win\pytm_win\lib\site-packages\winrt\__init__.py", line 4, in <module>
    _winrt.init_apartment()
RuntimeError: Cannot change thread mode after it is set.>

Could someone help us to get it solved?

Regards,
Vinoth P B

**Comment by AlexGuo1998** [comment]
Hi, same error here but when running scripts with a debugger attached.
Just run the demo code with PyCharm ([pydevd](https://github.com/fabioz/PyDev.Debugger)) or VSCode debugger ([debugpy](https://github.com/microsoft/debugpy)):
```python
import winrt.windows.foundation as wf
```
And it prints (in VSCode)
```
Traceback (most recent call last):
  File "C:\Program Files\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy\__main__.py", line 45, in <module>
    cli.main()
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 430, in main
    run()
  File "c:\Users\xxx\.vscode\extensions\ms-python.python-2020.9.114305\pythonFiles\lib\python\debugpy/..\debugpy\server\cli.py", line 267, in run_file
    runpy.run_path(options.target, run_name=compat.force_str("__main__"))
  File "C:\Program Files\Python37\lib\runpy.py", line 263, in run_path
    pkg_name=pkg_name, script_name=fname)
  File "C:\Program Files\Python37\lib\runpy.py", line 96, in _run_module_code
    mod_name, mod_spec, pkg_name, script_name)
  File "C:\Program Files\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "c:\Users\xxx\PycharmProjects\test\winrt_demo.py", line 9, in <module>
    import winrt.windows.foundation as wf
  File "C:\Users\xxx\PycharmProjects\test\venv\lib\site-packages\winrt\__init__.py", line 4, in <module>
    _winrt.init_apartment()
RuntimeError: 无法在设置线程模式后对其加以更改。
```
My system language is Chinese, the last line translates to `Cannot change thread mode after it is set`.
Could you please investigate this?

**Comment by BenJKuhn** [comment]
I may not get time to debug this right away, but I can give you a few quick tips that might help> WinRT users RoInitialize, which is basically just a wrapper around CoInitialize/ CoInitializeEx. If _winrt.init_apartment is failing due to having already been set, you should be able to debug by running the process under the VS or WinDbg debugger, and setting a breakpoint on three fucntions: combase!CoInitialize, combase!RoInitialize, and combase!CoInitializeEx. You might only actually need the last one. The error suggests that something else you're importing is already initializing COM, but defaulting to a different mode. Breaking on combase entry points should allow you to see when that's happening, and see which modes are being set.

PyWinRT should be tolerant of running in different modes though. This is something that I should be able to address (and probably add an API to check mode, since it will matter for some apps). PyWinRT defaults to MTA. It's likely the case that some other module that you're loading defaulted to STA and loaded first. I'll leave the issue open to address this in a future update. In the meantime I hope that helps you diagnose your issue.

**Comment by rye761** [comment]
I have run into this issue as well. In this case, I was able to get `pythoncom` to load using MTA by specifying `sys.coinit_flags = 0` but then that breaks the Qt GUI. Not sure if that's because Qt is then trying to load STA and getting the same error WinRT is getting when it tries to load MTA. Error is `Qt warning: QWindowsContext: OleInitialize() failed:  "COM error 0xffffffff80010106 RPC_E_CHANGED_MODE (Unknown error 0x080010106)"` Would probably be best if WinRT also respected the sys.coinit_flags var.

**Comment by BenJKuhn** [comment]
I like the suggestion. We're not going to have time to look at this soon, so I'm going to mark this as a good first issue. The code in question is currently using C++ /WinRT's init_apartment helper. See:
https://github.com/microsoft/xlang/blob/master/src/tool/python/strings/module_methods.cpp

The work would be to change to check the python property, and call CoInitializeEx. It should also probably handle RPC_E_CHANGED_MODE gracefully and avoid calling CoUninitialize in that case as well.

**Comment by WT2** [comment]
Hello folks, did you find a solution for this one?
Thanks in advance :)

**Comment by rye761** [comment]
> 
> 
> Hello folks, did you find a solution for this one?
> Thanks in advance :)

We found that simply using the API on a separate thread worked for the minimal use it is being used for in Anki.

**Comment by dlech** [comment]
Ideally, importing modules should not have side effects. Having `winrt` call `_winrt.init_apartment()` on init violates this principal. 

So, I think the options here are:
1. Require users to manually call `_winrt.init_apartment()` if needed, e.g. not needed when using a GUI toolkit (breaking change).
2. Add an environment variable check (or similar mechanism) to allow opting out of the automatic init.
3. Recommend that users call `_winrt.deinit_apartment()` before using a GUI toolkit or other COM interop code that initializes COM.

**Comment by zerkerX** [comment]
This defect also caused us a bit of headache in our Sphinx (autodoc) documentation generation. We have a series of programs and libraries on our program; while none of the runtime combinations are problematic, the combined imports generating our documentation *is*. Since this dependency is only needed inside a function body, we ended up putting try/except around the import to work around this.

**Comment by kennykerr** [comment]
Please see this repo for Python support: https://github.com/pywinrt/pywinrt

**Comment by jamiemaclennan** [comment]
It's amazing that this can go unfixed.  The code on the WinRT pypi page (https://pypi.org/project/winrt/) won't run in VSCode.  Going to the file that calls init_apartment has a big WARNING: Please don't edit

How is any dev to know what they're supposed to do here?

**Comment by dlech** [comment]
Use https://pypi.org/project/winsdk/ instead of https://pypi.org/project/winrt/.
