### ISSUE TITLE
Relationships between xlang and grpc

### ISSUE THREAD

**Issue by raffaeler** [microsoft/xlang#73]
How does xlang relate to the grpc project?
https://github.com/grpc/grpc
From what I see grpc targets protocol buffers (and still make use of IDL) while xlang is meant to solve in-process bindings.
Anyway, I believe there is an opportunity to bridge the two.
Comments?

**Comment by phoyd** [comment]
I understand xlang as a way to describe and use application programming interfaces by defining a standard set of language elements to describe the _specification patterns_ an API usually exposes in specific terms (interfaces, delegates, a fixed set of primitive types etc.). 

For example: The streams library from the C standard gives us a "FILE*" type and a bunch of functions which operate on them. However, most of the information on how to use these function is in documentation and not exposed in the structure of the API itself: 

* there is one function to construct a kind (fopen), but what is freopen() then? 
* is fclose() a "delete" or a "close and reopen" method? 
* what is the relation between the buffer and the size parameters in fread/fwrite.
* The return values of fopen(), fread() and fclose() are used to signal an error. But the return types are FILE*, size_t and int. "0" means OK for fclose, but error for fopen(). 

And it doesn't stop here. The next API has a different naming schemes, error reporting schemes, requirements, namespace prefixes and it's own rules on the lifetime of things. They're all kind of leaky, because they're exposing details of their implementation and on the other hand they all make use of the same stereotypes (construction, destruction, error return, passing data of size known at runtime only, call and callee responsibilities )

xlang allows us to speak of an API without knowing how all these stereotypes are done in a specific case. There is a pattern for API namespaces, it defines how to express the construction of thing, how errors are reported, how asynchronous calls are made, how identifiers should be named (so that you can automatically perform conversions for different naming conventions). Remember how every library with callbacks has its own scheme on how to pass a "user" pointer to the callback? What are the rules for the lifetime of the data behind the user pointer? xlang replaces under-specified callbacks with delegates, which know about user data and their lifetime.

And finally, and that is the beautiful thing about it, xlang won't patronize with the interfaces it manages. It just tells you anything you need to know about about the interface, so that you can automatically map (without putting any extra knowledge into it) the interface to the API convention that fits your target language or framework. 

gRPC would then simply be a new mapping of xlang, presumably with an automatic tool to create a gRPC service from a xlang specification and some manual work to expose an exisiting gRPC services in xlang terms.

**Comment by devhawk** [comment]
Great summary @phoyd.

I would add that we have clearly stated that xlang is [*NOT* porting DCOM](https://github.com/Microsoft/xlang/#what-xlang-is-not). We know that cross process/cross machine communication is likely an important scenario for xlang, but we are only focused on in process component scenarios right now. 

I can think of lots of ways to combine xlang with existing communication technology like [gRPC](https://grpc.io/) or [OpenAPI](https://swagger.io/specification/), but would love to hear more ideas from the broader community.

**Comment by BrentRe** [comment]
I agree. Great summary. I would add that interfaces are (mostly) an implementation detail within xlang. Most developers never need to think about interfaces. Instead, they think about classes.

xlang defines an language-agnostic object-oriented, hierarchical class-based type system. xlang tooling produces language bindings for various languages, enabling those languages to use xlang types / call xlang APIs. Additionally, xlang tooling also produces source code to wrap your existing libraries (written in various languages) so your library can be called by xlang client language projections.


maps (projects) APIs defined using that type system to various languages. Additionally, xlang tooling produces the

**Comment by raffaeler** [comment]
Very interesting perspective @phoyd .
I was not arguing they overlap, but just 'dreaming' about connecting them in order to expand the inter-language tools instead of having to just pick one of the two.
I think there is an opportunity to use gRPC (or other libraries) as a proxy/stub for running a certain component out of process or even remotely (I was a DCOM user but it's a long time I moved from an RPC-style architecture to HTTP/rest).

**Comment by devhawk** [comment]
I agree 100% @raffaeler on the opportunity to combine xlang + gRPC or other similar libraries. We're just focused on in proc scenarios first. In proc is obviously a requirement before tackling RPC scenarios. 

If you wouldn't mind writing up your thoughts as a [design note](https://github.com/Microsoft/xlang/blob/master/design_notes/XDN00%20-%20Design%20Note%20Process.md) or as further comments on this thread - we'd love the input!

**Comment by raffaeler** [comment]
I totally subscribe that in-proc comes first, @devhawk ... no hurry at all.
Maybe it's a bit too early for a design note, but I can get there as soon as the brainstorming is a bit more evolved.
Thanks
