### ISSUE TITLE
Proposal: Requesting support for ANSI-C

### ISSUE THREAD

**Issue by ghost** [microsoft/xlang#732]
# Proposal: Support for ANSI-C based development

## Summary
Requesting support for working with WindowsUI using ANSI-C instead of only C++17 and beyond.

## Rationale
Since WindowsUI is built primarily using COM objects, programming the same using any language should be possible.
Win32, the core API for writing Windows applications since Windows3.1 was extended to support 64-bit systems with additions to the API to support newer technologies brought-in Windows10 which is being called WinAPI currently is primarily an ANSI-C based API.
It would be desirable and advantageous to provide support to develop WindowsUI based interfaces using ANSI-C so that an application developer need not have to switch between more than 1 language (ANSI-C) while developing a Windows app using WinAPI and WindowsUI.

* Windows application developers building apps upon the WinAPI layer need not switch to a secondary language, i.e. C++.
* C++ is a faster moving target as compared to ANSI-C as far as the Visual Studio compiler support goes.

## Scope
Must include support for ANSI-C upto the 1999 standard.
Should provide adequate documentation and example code.
Could provide support for tooling for ANSI-C up to the 1999 standard.

**Comment by BenJKuhn** [comment]
The ABI tool provides access to WinRT interfaces for C, but it's not what we typically refer to as a "projection" since it's raw API access with no frills or conveniences:
https://www.nuget.org/packages/Microsoft.Windows.AbiWinRT/

In theory, you could write a XAML app with that. In practice, you won't have a good time.
1) Writing to the ABI exposes the complexities of the XAML inheritance-as-aggregation model, and is difficult to code against directly.
2) The XAML compiler won't generate code for ANSI C.

At this point there isn't sufficient interest to justify the significant cost of building out a projection that simplifies UI support. If there are bugs in the ABI writer that prevent general WinRT usage from C, please bring them to our attention and we'll investigate.

**Comment by mayureshkathe** [comment]
@BenJKuhn can you confirm that C++11/14 too can be used to work with WindowsUI? Or is C++17 the minimum required version of C++?

**Comment by Jaiganeshkumaran** [comment]
C++ 11/14 can be used via WRL or C++/CX if you really wanted to. It's C++/WinRT that requires C++ 17 or later because it relies on the newer features to work.

**Comment by mayureshkathe** [comment]
@Jaiganeshkumaran if I recollect it right, C++/WinRT, as created by Kenny Kerr, had support for both C as well as C++11. Would it be asking for too much from the team to request support up to at least C++11/14?

**Comment by Jaiganeshkumaran** [comment]
> @Jaiganeshkumaran if I recollect it right, C++/WinRT, as created by Kenny Kerr, had support for both C as well as C++11. Would it be asking for too much from the team to request support up to at least C++11/14?

C++/WinRT did have C++11 support when it was originally created as Modern however it no longer does because C++/WinRT uses features that are only available in C++17.
