### ISSUE TITLE
Adding support for Golang?

### ISSUE THREAD

**Issue by bundgaard** [microsoft/xlang#735]
Hi

Been new to this repository and following @kennykerr blog about adding support for Rust and creating the Windows crate;
Is there any interest in adding Golang Windows Support ?

Thanks

**Comment by bundgaard** [comment]
Reading through the design specs, I see some problems using Go for this.
Generics, overload of methods.

**Comment by jonwis** [comment]
Can you give an example of a method that might not work? Projections are expected to "make it right." 

At least for Windows APIs with overloads, we require overloading on parameter count rather than by type, and we require providing a method name for the overload.  So for example:

```idl
runtimeclass MyType
{
    void Compute(String a);
    
    [method_name("ComputeWithString")]
    void Compute(String a, String b);
}
```

For C++/WinRT, you could write:

```c++
MyType mt;
mt.Compute(L"foo");
mt.Compute(L"foo", L"bar");
```

For languages without overloads at all, the projection would emit the "method name" instead which has to be unique:

```go
MyType mt;
mt.Compute("foo");
mt.ComputeWithString("foo", "bar");
```

WinRT metadata does support overloading on type, though, which we've tried to not use for Windows APIs. So this is technically possible:

```idl
runtimeclass MyType
{
    void Compute(String a);
    
    [method_name("ComputeWithInt32")]
    void Compute(Int32 a);
}
```

Those C++/WinRT customers would still say:

```c++
MyType mt;
mt.Compute(L"foo");
mt.Compute(6);
```

And JavaScript (no overloading on type) says:

```javascript
MyType mt;
mt.compute("foo");
my.computeWithInt32(6);
```

While Go says:

```javascript
MyType mt;
mt.Compute("foo");
my.ComputeWithInt32(6);
```

**Comment by bundgaard** [comment]
I was looking at it from a hard rule that we needed overload on the same method name, as that would not be available in Go, but with your examples, if we are fine by using longer method names, then we actually can pull it off.

That makes me happy, and I appreciate your feedback.

**Comment by jonwis** [comment]
Great! In the cases where a `[method_name]` is not available, a projection could still do a reasonable thing and generate its own suffixes, like `mt.Compute("foo")` or `mt.Compute2("foo")`. The projection's implementation translates that into "get the interface with id IID_IMyType, then call vtable slot 1 or 2."

To your earlier question of "is there interest" - yes, definitely there's interest! If you'd like advice on how to add a Go projection please don't hesitate to add more questions here, stand up a new repo, etc.  Check out the repo's landing page for a list of projections under development.

**Comment by aymanbagabas** [comment]
This is already possible using [go-ole](https://github.com/go-ole/go-ole) but I'm not sure how big of a task this is. [tinygo-org/bluetooth](https://github.com/tinygo-org/bluetooth/tree/release/winbt) implements a portion of the [bluetooth advertisement interface](https://docs.microsoft.com/en-us/uwp/api/windows.devices.bluetooth.advertisement?view=winrt-22000) using [go-ole](https://github.com/go-ole/go-ole). I'm interested in interacting with the WinRT API from go and would love to see a WinRT projection for Golang.
